// Auto-generated by generate-static-data.js - DO NOT EDIT MANUALLY
export interface Post {
  id: number;
  title: string;
  slug: string;
  content: string;
  created_at: number;
}

export const POSTS_DATA = [
  {
    "id": 49,
    "title": "Hello World",
    "slug": "hello-world",
    "content": "<p>Welcome to my blog built with Next.js, Tailwind and Drizzle ORM.</p>",
    "created_at": 1781690696
  },
  {
    "id": 50,
    "title": "Second Post",
    "slug": "second-post",
    "content": "<p>This is another post.</p>",
    "created_at": 1781690696
  }
] as const;

export function getAllPosts() {
  return POSTS_DATA;
}

export function getPostBySlug(slug: string) {
  return POSTS_DATA.find((p) => p.slug === slug);
}
