// Auto-generated by generate-static-data.ts - DO NOT EDIT MANUALLY
export interface Post {
  id: number;
  slug: string;
  title: string;
  content: string;
  created_at: number;
  images: Array<{
    original: string;
    src: string;
    srcset: string;
    sizes: string;
    blurDataUri: string;
    width: number | null;
    height: number | null;
  }>;

}

export const POSTS_DATA = [
  {
    "id": 1,
    "title": "Hello World",
    "slug": "hello-world",
    "content": "<p>Welcome to my blog built with Next.js, Tailwind and Drizzle ORM.</p>",
    "created_at": 1782516986,
    "series": null,
    "series_order": null,
    "images": []
  },
  {
    "id": 2,
    "title": "Second Post",
    "slug": "second-post",
    "content": "<p>This is another post.</p>",
    "created_at": 1782516986,
    "series": null,
    "series_order": null,
    "images": []
  }
] as const;

export function getAllPosts() {
  return POSTS_DATA;
}

export function getPostBySlug(slug: string) {
  return POSTS_DATA.find((p) => p.slug === slug);
}
